#' prosstt: A package for evaluating lineage tree predictions on PROSSTT
#' simulations.
#'
#' The prosstt package provides three categories of important functions:
#' I/O & convenience functions, evaluation functions, and plotting functions
#' 
#' @section I/O and convenience:
#' Functions to read PROSSTT simulation files and write result files, functions
#' to run multiple analysis calls together.
#'
#' @section Evaluation:
#' prosstt implements a number of external cluster evaluation methods and some
#' graph functions to evaluate branch assignment and pseudotime prediction for
#' simulations generated by the python PROSSTT package.
#'
#' @section Plotting:
#' prosstt includes a function to calculate and plot a 2D overview of the
#' simulation that preserves the topology while allowing for the branch
#' or pseudotime prediction to be visualized as color.
#'
#' @docType package
#' @name prosstt
NULL